use super::*;

fn generate_rust_code(tokens: &ExtractedTokens) -> String {
    let mut out = String::new();

    out.push_str("// Auto-generated by egui_expressive figma exporter\n");
    out.push_str("// Source: Figma Tokens export\n\n");

    out.push_str(
        "use egui_expressive::{AccentColors, DesignTokens, SpacingScale, SurfacePalette};\n",
    );
    out.push_str("use egui::Color32;\n\n");

    out.push_str("pub fn design_tokens() -> DesignTokens {\n");
    out.push_str("    DesignTokens {\n");

    // Surface palette
    out.push_str("        surface: SurfacePalette {\n");
    for stop in &SURFACE_STOPS {
        let color = tokens.surface_color(stop).unwrap_or(ParsedColor {
            r: 0,
            g: 0,
            b: 0,
            a: 255,
        });
        out.push_str(&format!(
            "            s{}: {},\n",
            stop,
            color.to_color32_expr()
        ));
    }
    out.push_str("        },\n");

    // Accent colors
    out.push_str("        accent: AccentColors {\n");
    for name in &ACCENT_NAMES {
        let color = tokens.accent_color(name).unwrap_or(ParsedColor {
            r: 0,
            g: 0,
            b: 0,
            a: 255,
        });
        out.push_str(&format!(
            "            {}: {},\n",
            name,
            color.to_color32_expr()
        ));
    }
    out.push_str("        },\n");

    // Spacing scale
    out.push_str("        spacing: SpacingScale {\n");
    for name in &SPACING_NAMES {
        let value = tokens.spacing.get(*name).copied().unwrap_or(0.0);
        out.push_str(&format!("            {}: {},\n", name, value));
    }
    out.push_str("        },\n");

    // Rounding: use "md" as base rounding, "lg" as panel_rounding
    let rounding = tokens.rounding.get("md").copied().unwrap_or(4.0);
    let panel_rounding = tokens.rounding.get("lg").copied().unwrap_or(8.0);
    out.push_str(&format!("        rounding: {},\n", rounding));
    out.push_str(&format!("        panel_rounding: {},\n", panel_rounding));

    out.push_str("    }\n");
    out.push_str("}\n");

    out
}

/// Parse Figma Tokens plugin JSON (or Figma REST API styles JSON) and emit Rust source
/// code for [`crate::style::DesignTokens`].
pub fn figma_tokens_to_rust(json: &str) -> Result<String, FigmaExportError> {
    let value: serde_json::Value =
        serde_json::from_str(json).map_err(|e| FigmaExportError::ParseError(e.to_string()))?;

    // Check if this is a Figma REST API styles response
    if let Some(_styles_response) = value.get("styles") {
        if let Ok(resp) = serde_json::from_str::<FigmaStylesResponse>(json) {
            if let Some(styles) = resp.styles {
                return generate_from_figma_styles(&styles);
            }
        }
        // If styles exists but didn't parse as expected, try token groups anyway
    }

    // Try as Figma Tokens plugin JSON
    let tokens = extract_tokens_from_figma_tokens(&value)?;
    Ok(generate_rust_code(&tokens))
}

/// Generate Rust code from Figma REST API styles response.
/// This handles the simpler FILL-only export where we don't have actual color values
/// stored — we emit placeholder comments for manual fill-in.
pub(crate) fn generate_from_figma_styles(
    styles: &[FigmaStyleEntry],
) -> Result<String, FigmaExportError> {
    let mut out = String::new();

    out.push_str("// Auto-generated by egui_expressive figma exporter\n");
    out.push_str("// Source: Figma REST API styles export\n");
    out.push_str("// NOTE: Figma REST API does not include actual color values.\n");
    out.push_str("//       Replace the placeholder Color32::DEFAULT values below.\n\n");

    out.push_str(
        "use egui_expressive::{AccentColors, DesignTokens, SpacingScale, SurfacePalette};\n",
    );
    out.push_str("use egui::Color32;\n\n");

    out.push_str("pub fn design_tokens() -> DesignTokens {\n");
    out.push_str("    DesignTokens {\n");

    // Group styles by prefix
    let mut surface_entries = Vec::new();
    let mut accent_entries = Vec::new();

    for style in styles {
        if style.style_type != "FILL" {
            continue;
        }
        let parts: Vec<&str> = style.name.split('/').collect();
        if parts.len() >= 2 {
            let prefix = parts[0];
            let name = parts[1..].join("/");
            match prefix {
                "surface" => surface_entries.push((name, style.description.clone())),
                "accent" => accent_entries.push((name, style.description.clone())),
                _ => {}
            }
        }
    }

    // Surface palette — emit all stops found, placeholder for rest
    out.push_str("        surface: SurfacePalette {\n");
    for stop in &SURFACE_STOPS {
        let entry = surface_entries.iter().find(|(n, _)| n == *stop);
        if let Some((_, desc)) = entry {
            let comment = desc.as_deref().unwrap_or("");
            if !comment.is_empty() {
                out.push_str(&format!("            // s{}: \"{}\"\n", stop, comment));
            }
            out.push_str(&format!(
                "            s{}: Color32::from_rgba_unmultiplied(0, 0, 0, 255), // Replace with actual color from design tokens\n",
                stop
            ));
        } else {
            out.push_str(&format!(
                "            s{}: Color32::from_rgba_unmultiplied(0, 0, 0, 255), // Replace with actual color from design tokens\n",
                stop
            ));
        }
    }
    out.push_str("        },\n");

    // Accent colors
    out.push_str("        accent: AccentColors {\n");
    for name in &ACCENT_NAMES {
        let entry = accent_entries.iter().find(|(n, _)| n == name);
        if let Some((_, desc)) = entry {
            let comment = desc.as_deref().unwrap_or("");
            if !comment.is_empty() {
                out.push_str(&format!("            // {}: \"{}\"\n", name, comment));
            }
        }
        out.push_str(&format!(
            "            {}: Color32::from_rgba_unmultiplied(0, 0, 0, 255), // Replace with actual color from design tokens\n",
            name
        ));
    }
    out.push_str("        },\n");

    // Default spacing and rounding (no data from REST API)
    out.push_str("        spacing: SpacingScale {\n");
    for name in &SPACING_NAMES {
        out.push_str(&format!(
            "            {}: 0.0, // Replace with actual spacing value from design tokens\n",
            name
        ));
    }
    out.push_str("        },\n");

    out.push_str("        rounding: 4.0, // Replace with actual rounding from design tokens\n");
    out.push_str(
        "        panel_rounding: 8.0, // Replace with actual panel rounding from design tokens\n",
    );

    out.push_str("    }\n");
    out.push_str("}\n");

    Ok(out)
}

// ─── Runtime Deserializer ────────────────────────────────────────────────────
