use super::*;

/// Generate a complete Rust source file from a list of LayoutNodes.
pub fn generate_rust(
    fn_name: &str,
    artboard_w: f32,
    artboard_h: f32,
    nodes: &[LayoutNode],
    bg_color: Option<Color32>,
    state_struct_name: Option<&str>,
    token_map: Option<&HashMap<String, Color32>>,
) -> String {
    let mut output = String::new();

    // Add imports at the top
    output.push_str("#[allow(unused_imports)]\n");
    output.push_str("use egui::{Color32, RichText, Ui, Vec2, Rect, Pos2, Stroke, vec2, pos2};\n");
    output.push_str("#[allow(unused_imports)]\n");
    output.push_str("use egui_expressive::{hstack, vstack, ShapeBuilder, LayeredPainter};\n");
    output.push_str("#[allow(unused_imports)]\n");
    output.push_str("use super::tokens;\n");
    output.push_str("#[allow(unused_imports)]\n");
    output.push_str("use super::state::*;\n");
    output.push('\n');

    output.push_str("// Auto-generated by egui_expressive\n");
    output.push_str(&format!(
        "// Artboard: \"{}\" ({} × {} px)\n",
        fn_name, artboard_w, artboard_h
    ));
    output.push_str("\n#[allow(unused_variables, dead_code)]\n");

    // Generate function signature with or without state
    if let Some(state_name) = state_struct_name {
        let action_name = state_name.replace("State", "Action");
        output.push_str(&format!(
            "pub fn draw_{}(ui: &mut Ui, state: &mut {}) -> Option<{}> {{\n",
            sanitize_fn_name(fn_name),
            state_name,
            action_name
        ));
    } else {
        output.push_str(&format!(
            "pub fn draw_{}(ui: &mut Ui) {{\n",
            sanitize_fn_name(fn_name)
        ));
    }

    output.push_str("    let origin = ui.cursor().min;\n");
    output.push_str(&format!(
        "    ui.allocate_space(egui::vec2({:.1}, {:.1}));\n",
        artboard_w, artboard_h
    ));
    output.push_str(&format!(
        "    let artboard_rect = egui::Rect::from_min_size(origin, egui::vec2({:.1}, {:.1}));\n",
        artboard_w, artboard_h
    ));
    output.push_str("    let painter = ui.painter_at(artboard_rect);\n");
    output.push('\n');

    // Background
    if let Some(bg) = bg_color {
        output.push_str("    // Background\n");
        output.push_str(&format!(
            "    painter.rect_filled(\n        egui::Rect::from_min_size(origin, egui::vec2({:.1}, {:.1})),\n",
            artboard_w, artboard_h
        ));
        output.push_str("        0.0,\n");
        output.push_str(&format!(
            "        egui::Color32::from_rgb({}, {}, {}),\n",
            bg.r(),
            bg.g(),
            bg.b()
        ));
        output.push_str("    );\n");
        output.push('\n');
    }

    // Generate code for each top-level node
    for node in nodes {
        output.push_str(&generate_node(node, 4, token_map));
    }

    if state_struct_name.is_some() {
        output.push_str("    None\n");
    }

    output.push_str("}\n");

    output
}

/// Generate egui font setup code for loading custom fonts.
///
/// Returns a Rust function `setup_fonts(ctx: &egui::Context)` that registers
/// the given font families using `egui::FontDefinitions`. Each family name
/// maps to a font file expected at `assets/fonts/<family>.ttf`.
///
/// # Example output
/// ```ignore
/// use egui::{FontData, FontDefinitions, FontFamily};
///
/// pub fn setup_fonts(ctx: &egui::Context) {
///     let mut fonts = FontDefinitions::default();
///     // Font: Inter
///     fonts.font_data.insert(
///         "inter".to_owned(),
///         FontData::from_static(include_bytes!("../assets/fonts/Inter.ttf")),
///     );
///     fonts.families.entry(FontFamily::Name("Inter".into()))
///         .or_default()
///         .push("inter".to_owned());
///     ctx.set_fonts(fonts);
/// }
/// ```
pub fn generate_font_setup(font_families: &[&str]) -> String {
    if font_families.is_empty() {
        return String::new();
    }

    let mut out = String::new();
    out.push_str("use egui::{FontData, FontDefinitions, FontFamily};\n\n");
    out.push_str("/// Register custom fonts with egui. Call once from App::new().\n");
    out.push_str("pub fn setup_fonts(ctx: &egui::Context) {\n");
    out.push_str("    let mut fonts = FontDefinitions::default();\n\n");

    for family in font_families {
        let safe_name = family.replace(['-', ' '], "_").to_lowercase();
        out.push_str(&format!("    // Font: {}\n", family));
        out.push_str(&format!(
            "    fonts.font_data.insert(\n        \"{}\".to_owned(),\n",
            safe_name
        ));
        out.push_str(&format!(
            "        FontData::from_static(include_bytes!(\"../assets/fonts/{}.ttf\")),\n    );\n",
            family
        ));
        out.push_str(&format!(
            "    fonts.families.entry(FontFamily::Name(\"{}\".into()))\n",
            family
        ));
        out.push_str(&format!(
            "        .or_default()\n        .push(\"{}\".to_owned());\n\n",
            safe_name
        ));
    }

    out.push_str("    ctx.set_fonts(fonts);\n");
    out.push_str("}\n");
    out
}

pub(crate) fn sanitize_fn_name(name: &str) -> String {
    const RUST_KEYWORDS: &[&str] = &[
        "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn",
        "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref",
        "return", "self", "Self", "static", "struct", "super", "trait", "true", "type", "unsafe",
        "use", "where", "while", "async", "await", "dyn", "abstract", "become", "box", "do",
        "final", "macro", "override", "priv", "typeof", "unsized", "virtual", "yield",
    ];
    let sanitized: String = name
        .to_lowercase()
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    // Remove leading/trailing underscores, collapse multiple underscores
    let sanitized = sanitized.trim_matches('_').to_string();
    let sanitized = {
        let mut s = String::new();
        let mut prev_underscore = false;
        for c in sanitized.chars() {
            if c == '_' {
                if !prev_underscore {
                    s.push(c);
                }
                prev_underscore = true;
            } else {
                s.push(c);
                prev_underscore = false;
            }
        }
        s
    };
    // Handle empty result
    let sanitized = if sanitized.is_empty() {
        "function".to_string()
    } else {
        sanitized
    };
    // Handle leading digit
    let sanitized = if sanitized.starts_with(|c: char| c.is_ascii_digit()) {
        format!("f_{}", sanitized)
    } else {
        sanitized
    };
    // Handle Rust keywords
    if RUST_KEYWORDS.contains(&sanitized.as_str()) {
        format!("{}_", sanitized)
    } else {
        sanitized
    }
}
