use super::*;

fn shaped_glyph_contour_expr(contour: &crate::scene::PathContour) -> String {
    let points = contour
        .points
        .iter()
        .map(|point| format!("({:.1}, {:.1})", point.x, point.y))
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "egui_expressive::scene::PathContour {{ points: egui_expressive::scene::path_points(&[{}]), closed: {} }}",
        points,
        contour.closed
    )
}

fn shaped_glyph_contours_expr(contours: &[crate::scene::PathContour]) -> String {
    if contours.is_empty() {
        "vec![]".to_string()
    } else {
        format!(
            "vec![{}]",
            contours
                .iter()
                .map(shaped_glyph_contour_expr)
                .collect::<Vec<_>>()
                .join(", ")
        )
    }
}

/// Generate a complete Rust source file from a list of LayoutNodes.
/// Returns a String containing valid Rust code.
pub fn generate_rust(
    fn_name: &str,
    artboard_w: f32,
    artboard_h: f32,
    nodes: &[LayoutNode],
    bg_color: Option<Color32>,
    state_struct_name: Option<&str>,
    token_map: Option<&HashMap<String, Color32>>,
) -> String {
    let mut output = String::new();

    // Add imports at the top
    output.push_str("#[allow(unused_imports)]\n");
    output.push_str("use egui::{Color32, RichText, Ui, Vec2, Rect, Pos2, Stroke, vec2, pos2};\n");
    output.push_str("#[allow(unused_imports)]\n");
    output.push_str("use egui_expressive::{hstack, vstack, ShapeBuilder, LayeredPainter};\n");
    output.push_str("#[allow(unused_imports)]\n");
    output.push_str("use super::tokens;\n");
    output.push_str("#[allow(unused_imports)]\n");
    output.push_str("use super::state::*;\n");
    output.push('\n');

    output.push_str("// Auto-generated by egui_expressive\n");
    output.push_str(&format!(
        "// Artboard: \"{}\" ({} × {} px)\n",
        fn_name, artboard_w, artboard_h
    ));
    output.push_str("\n#[allow(unused_variables, dead_code)]\n");

    // Generate function signature with or without state
    if let Some(state_name) = state_struct_name {
        let action_name = state_name.replace("State", "Action");
        output.push_str(&format!(
            "pub fn draw_{}(ui: &mut Ui, state: &mut {}) -> Option<{}> {{\n",
            sanitize_fn_name(fn_name),
            state_name,
            action_name
        ));
    } else {
        output.push_str(&format!(
            "pub fn draw_{}(ui: &mut Ui) {{\n",
            sanitize_fn_name(fn_name)
        ));
    }

    output.push_str("    let origin = ui.cursor().min;\n");
    output.push_str(&format!(
        "    ui.allocate_space(egui::vec2({:.1}, {:.1}));\n",
        artboard_w, artboard_h
    ));
    output.push_str(&format!(
        "    let artboard_rect = egui::Rect::from_min_size(origin, egui::vec2({:.1}, {:.1}));\n",
        artboard_w, artboard_h
    ));
    output.push_str("    let painter = ui.painter_at(artboard_rect);\n");
    output.push('\n');

    // Background
    if let Some(bg) = bg_color {
        output.push_str("    // Background\n");
        output.push_str(&format!(
            "    painter.rect_filled(\n        egui::Rect::from_min_size(origin, egui::vec2({:.1}, {:.1})),\n",
            artboard_w, artboard_h
        ));
        output.push_str("        0.0,\n");
        output.push_str(&format!(
            "        egui::Color32::from_rgb({}, {}, {}),\n",
            bg.r(),
            bg.g(),
            bg.b()
        ));
        output.push_str("    );\n");
        output.push('\n');
    }

    // Generate code for each top-level node
    for node in nodes {
        output.push_str(&generate_node(node, 4, token_map));
    }

    if state_struct_name.is_some() {
        output.push_str("    None\n");
    }

    output.push_str("}\n");

    output
}

/// Generate egui font setup code for loading custom fonts.
///
/// Returns a Rust function `setup_fonts(ctx: &egui::Context)` that registers
/// the given font families using `egui::FontDefinitions`. Each family name
/// maps to a font file expected at `assets/fonts/<family>.ttf`.
///
/// # Example output
/// ```ignore
/// use egui::{FontData, FontDefinitions, FontFamily};
///
/// pub fn setup_fonts(ctx: &egui::Context) {
///     let mut fonts = FontDefinitions::default();
///     // Font: Inter
///     fonts.font_data.insert(
///         "inter".to_owned(),
///         FontData::from_static(include_bytes!("../assets/fonts/Inter.ttf")),
///     );
///     fonts.families.entry(FontFamily::Name("Inter".into()))
///         .or_default()
///         .push("inter".to_owned());
///     ctx.set_fonts(fonts);
/// }
/// ```
pub fn generate_font_setup(font_families: &[&str]) -> String {
    if font_families.is_empty() {
        return String::new();
    }

    let mut out = String::new();
    out.push_str("use egui::{FontData, FontDefinitions, FontFamily};\n\n");
    out.push_str("/// Register custom fonts with egui. Call once from App::new().\n");
    out.push_str("pub fn setup_fonts(ctx: &egui::Context) {\n");
    out.push_str("    let mut fonts = FontDefinitions::default();\n\n");

    for family in font_families {
        let safe_name = family.replace(['-', ' '], "_").to_lowercase();
        out.push_str(&format!("    // Font: {}\n", family));
        out.push_str(&format!(
            "    fonts.font_data.insert(\n        \"{}\".to_owned(),\n",
            safe_name
        ));
        out.push_str(&format!(
            "        FontData::from_static(include_bytes!(\"../assets/fonts/{}.ttf\")),\n    );\n",
            family
        ));
        out.push_str(&format!(
            "    fonts.families.entry(FontFamily::Name(\"{}\".into()))\n",
            family
        ));
        out.push_str(&format!(
            "        .or_default()\n        .push(\"{}\".to_owned());\n\n",
            safe_name
        ));
    }

    out.push_str("    ctx.set_fonts(fonts);\n");
    out.push_str("}\n");
    out
}

fn sanitize_fn_name(name: &str) -> String {
    const RUST_KEYWORDS: &[&str] = &[
        "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn",
        "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref",
        "return", "self", "Self", "static", "struct", "super", "trait", "true", "type", "unsafe",
        "use", "where", "while", "async", "await", "dyn", "abstract", "become", "box", "do",
        "final", "macro", "override", "priv", "typeof", "unsized", "virtual", "yield",
    ];
    let sanitized: String = name
        .to_lowercase()
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    // Remove leading/trailing underscores, collapse multiple underscores
    let sanitized = sanitized.trim_matches('_').to_string();
    let sanitized = {
        let mut s = String::new();
        let mut prev_underscore = false;
        for c in sanitized.chars() {
            if c == '_' {
                if !prev_underscore {
                    s.push(c);
                }
                prev_underscore = true;
            } else {
                s.push(c);
                prev_underscore = false;
            }
        }
        s
    };
    // Handle empty result
    let sanitized = if sanitized.is_empty() {
        "function".to_string()
    } else {
        sanitized
    };
    // Handle leading digit
    let sanitized = if sanitized.starts_with(|c: char| c.is_ascii_digit()) {
        format!("f_{}", sanitized)
    } else {
        sanitized
    };
    // Handle Rust keywords
    if RUST_KEYWORDS.contains(&sanitized.as_str()) {
        format!("{}_", sanitized)
    } else {
        sanitized
    }
}

/// Generate Rust code for a single LayoutNode (recursive).
pub fn generate_node(
    node: &LayoutNode,
    indent: usize,
    token_map: Option<&HashMap<String, Color32>>,
) -> String {
    let indent_str = " ".repeat(indent);
    let mut output = String::new();

    match node {
        LayoutNode::Row {
            gap,
            children,
            bg,
            id,
        } => {
            if let Some(bg_color) = bg {
                output.push_str(&format!(
                    "{}// Row: {}\n{}hstack!(ui, gap: {:.1}, {{\n",
                    indent_str, id, indent_str, gap
                ));
                output.push_str(&format!(
                    "{}let row_rect = egui::Rect::from_min_size(ui.cursor().min, egui::vec2(\n",
                    indent_str
                ));
                // Calculate row bounds
                let row_w: f32 = children.iter().map(get_node_width).sum();
                let row_h: f32 = children.iter().map(get_node_height).fold(0.0f32, f32::max);
                output.push_str(&format!("{}{:.1}, {:.1})),\n", indent_str, row_w, row_h));
                output.push_str(&format!(
                    "{});\n{}painter.rect_filled(row_rect, 0.0, {});\n",
                    indent_str,
                    indent_str,
                    color_to_token_or_literal(bg_color, token_map)
                ));
                for child in children {
                    output.push_str(&generate_node(child, indent + 4, token_map));
                }
                output.push_str(&format!("{}}});\n", indent_str));
            } else {
                output.push_str(&format!(
                    "{}// Row: {}\n{}hstack!(ui, gap: {:.1}, {{\n",
                    indent_str, id, indent_str, gap
                ));
                for child in children {
                    output.push_str(&generate_node(child, indent + 4, token_map));
                }
                output.push_str(&format!("{}}});\n", indent_str));
            }
        }
        LayoutNode::Column {
            gap,
            children,
            bg,
            id,
        } => {
            if let Some(bg_color) = bg {
                output.push_str(&format!(
                    "{}// Column: {}\n{}vstack!(ui, gap: {:.1}, {{\n{}",
                    indent_str, id, indent_str, gap, indent_str
                ));
                output.push_str(&format!(
                    "{}let col_rect = egui::Rect::from_min_size(ui.cursor().min, egui::vec2(\n",
                    indent_str
                ));
                let col_w: f32 = children.iter().map(get_node_width).fold(0.0f32, f32::max);
                let col_h: f32 = children.iter().map(get_node_height).sum();
                output.push_str(&format!("{}{:.1}, {:.1})),\n", indent_str, col_w, col_h));
                output.push_str(&format!(
                    "{});\n{}painter.rect_filled(col_rect, 0.0, {});\n",
                    indent_str,
                    indent_str,
                    color_to_token_or_literal(bg_color, token_map)
                ));
                for child in children {
                    output.push_str(&generate_node(child, indent + 4, token_map));
                }
                output.push_str(&format!("{}}});\n", indent_str));
            } else {
                output.push_str(&format!(
                    "{}// Column: {}\n{}vstack!(ui, gap: {:.1}, {{\n",
                    indent_str, id, indent_str, gap
                ));
                for child in children {
                    output.push_str(&generate_node(child, indent + 4, token_map));
                }
                output.push_str(&format!("{}}});\n", indent_str));
            }
        }
        LayoutNode::ScrollArea {
            vertical,
            horizontal,
            children,
            id,
        } => {
            output.push_str(&format!("{}// ScrollArea: {}\n", indent_str, id));
            let scroll_type = match (*vertical, *horizontal) {
                (true, false) => "egui::ScrollArea::vertical()",
                (false, true) => "egui::ScrollArea::horizontal()",
                (true, true) => "egui::ScrollArea::both()",
                (false, false) => "egui::ScrollArea::vertical()",
            };
            output.push_str(&format!(
                "{}{}.id_salt({:?}).show(ui, |ui| {{\n",
                indent_str, scroll_type, id
            ));
            for child in children {
                output.push_str(&generate_node(child, indent + 4, token_map));
            }
            output.push_str(&format!("{}}});\n", indent_str));
        }
        LayoutNode::Panel { side, children, id } => {
            output.push_str(&format!("{}// Panel: {:?} - {}\n", indent_str, side, id));
            let (width, height) = calculate_panel_dimensions(children, *side);
            output.push_str(&format!(
                "{}ui.allocate_ui(egui::vec2({:.1}, {:.1}), |ui| {{\n",
                indent_str, width, height
            ));
            for child in children {
                output.push_str(&generate_node(child, indent + 4, token_map));
            }
            output.push_str(&format!("{}}});\n", indent_str));
        }
        LayoutNode::Card {
            children,
            bg,
            rounding,
            id,
        } => {
            output.push_str(&format!("{}// Card: {}\n", indent_str, id));
            let (w, h) = calculate_card_dimensions(children);
            output.push_str(&format!(
                "{}let card_rect = egui::Rect::from_min_size(ui.cursor().min, egui::vec2({:.1}, {:.1}));\n",
                indent_str, w, h
            ));
            output.push_str(&format!(
                "{}ui.painter().rect_filled(card_rect, {:.1}, {});\n",
                indent_str,
                rounding,
                color_to_token_or_literal(bg, token_map)
            ));
            output.push_str(&format!("{}vstack!(ui, gap: 8.0, {{\n", indent_str));
            for child in children {
                output.push_str(&generate_node(child, indent + 4, token_map));
            }
            output.push_str(&format!("{}}});\n", indent_str));
        }
        LayoutNode::Button { label, id } => {
            output.push_str(&format!(
                "{}// Button: {}\n{}if ui.button(\"{}\").clicked() {{\n{}{}}}\n",
                indent_str, id, indent_str, label, indent_str, indent_str
            ));
        }
        LayoutNode::Label {
            text,
            size,
            color,
            font_family,
            id,
        } => {
            let color_str = if let Some(c) = color {
                color_to_token_or_literal(c, token_map)
            } else {
                "egui::Color32::from_gray(200)".to_string()
            };
            let font_chain = if let Some(family) = font_family {
                format!(".family(egui::FontFamily::Name(\"{}\".into()))", family)
            } else {
                String::new()
            };
            output.push_str(&format!(
                "{}// Label: {}\n{}ui.label(egui::RichText::new(\"{}\").size({:.1}).color({}){});\n",
                indent_str,
                id,
                indent_str,
                text.replace('"', "\\\""),
                size,
                color_str,
                font_chain
            ));
        }
        LayoutNode::TextEdit { placeholder, id } => {
            let sanitized_id = id.replace(['-', ' '], "_");
            output.push_str(&format!(
                "{}// TextEdit: {}\n{}ui.add(egui::TextEdit::singleline(&mut state.{})",
                indent_str, id, indent_str, sanitized_id
            ));
            if !placeholder.is_empty() {
                output.push_str(&format!(
                    ".hint_text(\"{}\")",
                    placeholder.replace('"', "\\\"")
                ));
            }
            output.push_str(");\n");
        }
        LayoutNode::Separator { id } => {
            output.push_str(&format!(
                "{}// Separator: {}\n{}ui.separator();\n",
                indent_str, id, indent_str
            ));
        }
        LayoutNode::Spacer { size, id } => {
            output.push_str(&format!(
                "{}// Spacer: {}\n{}ui.add_space({:.1});\n",
                indent_str, id, indent_str, size
            ));
        }
        LayoutNode::Badge { text, id } => {
            output.push_str(&format!(
                "{}// Badge: {}\n{}ui.label(egui::RichText::new(\"{}\")\n",
                indent_str,
                id,
                indent_str,
                text.replace('"', "\\\"")
            ));
            output.push_str(&format!("{}.size(11.0)\n", indent_str));
            output.push_str(&format!(
                "{}.color(egui::Color32::from_rgb(100, 200, 255)));\n",
                indent_str
            ));
        }
        LayoutNode::Icon { name, id } => {
            output.push_str(&format!(
                "{}// Icon: {} - {} (Icons are not natively supported yet; implement custom rendering here)\n",
                indent_str, id, name
            ));
        }
        LayoutNode::Shape {
            x,
            y,
            w,
            h,
            fill,
            id,
            style,
        } => {
            output.push_str(&generate_shape_node(
                indent, *x, *y, *w, *h, *fill, id, style, token_map,
            ));
        }
        LayoutNode::Image { id, .. } => {
            output.push_str(&format!(
                "{}// Raster/image {} is not supported and will not be exported.\n",
                indent_str, id
            ));
        }
        LayoutNode::Unknown { id, comment } => {
            output.push_str(&format!("{}// Unknown: {} ({})\n", indent_str, id, comment));
        }
        LayoutNode::RichScene(scene_node) => {
            output.push_str(&format!("{}// RichScene: {}\n", indent_str, scene_node.id));
            output.push_str(&format!("{}{{\n", indent_str));
            let inner = " ".repeat(indent + 4);
            output.push_str(&format!(
                "{}let node = {};\n",
                inner,
                generate_scene_node_code(scene_node, indent + 4)
            ));
            output.push_str(&format!("{}egui_expressive::scene::render_node(ui, &painter, origin.to_vec2(), &node, 1.0);\n", inner));
            output.push_str(&format!("{}}}\n", indent_str));
        }
    }

    output
}
